# Always validate the PR title AND all the commits
titleAndCommits: true
# Allows use of Merge commits (e.g. on GitHub: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: true
