nodeLinker: node-modules

packageExtensions:
  "@inkline/nuxt@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
      webpack: "*"
  "@nuxtjs/eslint-module@*":
    peerDependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
