name: Semantic PR title

concurrency:
  group: deploy-pr-${{ github.ref || github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
